### ISSUE TITLE
jdk版本以及增加test example

### ISSUE THREAD

**Issue by wgou** [hank-whu/turbo-rpc#1]
建议使用jdk7或8，现在9的普及貌似在大部分公司还没有体现
没有测试用例，大多mian方法测试本类，看起来有些不方便

**Comment by hank-whu** [comment]
好建议，后续会慢慢加上的。
现在还是新生儿状态，还需要一点时间成长。

**Comment by Viyond** [comment]
为什么是jdk9版本呢，依赖了9的新特性？

**Comment by hank-whu** [comment]
@Viyond 是的，用了一些 java 9 的新特性。不过不是非用不可，后续可能会考虑兼容 java 8
