### ISSUE TITLE
turbo-jmh benchmark 运行直接运行main方法报错JDWP

### ISSUE THREAD

**Issue by stillChina** [hank-whu/turbo-rpc#11]
# JMH version: 1.19
# VM version: JDK 9, VM 9+181
# VM invoker: /Library/Java/JavaVirtualMachines/jdk-9.jdk/Contents/Home/bin/java
# VM options: -agentlib:jdwp=transport=dt_socket,address=127.0.0.1:52004,suspend=y,server=n -javaagent:/Users/Gieey/Library/Caches/IntelliJIdea2018.1/captureAgent/debugger-agent.jar=file:/private/var/folders/xq/m3bcrwm14ls3_w7my2hnd0_80000gn/T/capture.props -Dfile.encoding=UTF-8
# Warmup: 5 iterations, 1 s each
# Measurement: 5 iterations, 1 s each
# Timeout: 10 min per iteration
# Threads: 8 threads, will synchronize iterations
# Benchmark mode: Throughput, ops/time
# Benchmark: rpc.turbo.benchmark.kryo.DefaultBenchmark.directByteBufferPage

# Run progress: 0.00% complete, ETA 00:03:20
# Fork: 1 of 1
ERROR: transport error 202: connect failed: Connection refused
ERROR: JDWP Transport dt_socket failed to initialize, TRANSPORT_INIT(510)
JDWP exit error AGENT_ERROR_TRANSPORT_INIT(197): No transports initialized [debugInit.c:730]
<forked VM failed with exit code 2>
<stdout last='20 lines'>
</stdout>
<stderr last='20 lines'>
ERROR: transport error 202: connect failed: Connection refused
ERROR: JDWP Transport dt_socket failed to initialize, TRANSPORT_INIT(510)
JDWP exit error AGENT_ERROR_TRANSPORT_INIT(197): No transports initialized [debugInit.c:730]
</stderr>

**Comment by hank-whu** [comment]
jmh 不支持 debug
