### ISSUE TITLE
请问 RPC Benchmark Round 1  是否有在测试 参数数据量大的情况下的表现，例如6mb的文本

### ISSUE THREAD

**Issue by zhuxiujia** [hank-whu/turbo-rpc#3]
请问 RPC Benchmark Round 1  是否有在测试 参数数据量大的情况下的表现，例如6mb的文本。
据说 dubbo 在使用 dubbo 协议下， 大文件表现不佳。。

**Comment by hank-whu** [comment]
没有，不过可以参考一下 listUser 这一项测试，这个算是比较大的 响应数据。
在 listUser 这项测试里，dubbo 原始协议性能确实非常差，是所有框架里最差的。
