### ISSUE TITLE
是否支持其它开发语言

### ISSUE THREAD

**Issue by tangramor** [hank-whu/turbo-rpc#4]
如果仅仅是java，就太局限了

**Comment by swiftplus** [comment]
语言限制貌似只跟协议相关吧，没有协议绑定语言就跟语言无关了。

**Comment by hank-whu** [comment]
默认的 tcp+protostuff 只支持 java，要支持其他语言只能自己实现。
不过每个接口都同时支持 http+rest，所有语言都能支持到，速度也还不错。
https://www.jianshu.com/p/18c95649b1a4
