### ISSUE TITLE
ConcurrentArrayList 的代码没看懂

### ISSUE THREAD

**Issue by swiftplus** [hank-whu/turbo-rpc#6]
ConcurrentArrayList中的add方法没看懂
`public void add(T value) {
		final int index = insertIndex();

		for (;;) {// like cas
			final Object[] before = values;
			before[index] = value;
			final Object[] after = values;

			if (before == after) {
				return;
			}
		}
	}
`
跟cas的相同点没看出来。

**Comment by hank-whu** [comment]
这个有点历史了，Java 1.7 时的做法，参考下面的链接：
https://github.com/dmlloyd/openjdk/blob/524a884c565c330a3ad8e94e10e1c40df6cfff4e/jdk/src/share/classes/java/util/concurrent/atomic/AtomicInteger.java#L160

**Comment by swiftplus** [comment]
jdk中的cas是值类型的，难道引用类型的也能cas。

**Comment by hank-whu** [comment]
不是一回事，只是类似。

ConcurrentArrayList 做法：获取修改前的 Object[] values，修改 values 里面的值，判断 values 引用是否被其他线程修改。如果没修改则终止，如果被修改则重复前面的步骤。

jdk 1.7 时代 cas 操作的流程：获取修改前的值 value，操作获取新值 next，cas 操作判断 value 值是否被其他线程修改。如果没修改则 next 值生效并终止，如果被修改则重复前面的步骤。
